version: "3.8"

# DEPLOYMENT NOTES FOR PORTAINER:
# 1. Upload all config files to a Git repository or directly to Portainer
# 2. Set environment variables DB_PASSWORD and DB_ROOT_PASSWORD when deploying through Portainer UI
# 3. No local shell scripts are required - this is a fully self-contained stack

services:
  db:
    image: mariadb:10.5
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1'
          memory: 1G
      labels:
        com.librenms.service: "database"
        com.librenms.description: "MariaDB database for LibreNMS"
    environment:
      MYSQL_DATABASE: librenms
      MYSQL_USER: librenms
      MYSQL_PASSWORD: ${DB_PASSWORD:-librenms_password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-librenms_root_password}
      # Use internal MariaDB secure-file-priv setting instead of command line
    volumes:
      - db-data:/var/lib/mysql
    configs:
      - source: mariadb_config_v4
        target: /etc/mysql/conf.d/custom.cnf
    networks:
      - librenms
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    # No command override - using config file instead

  redis:
    image: redis:6.2-alpine
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      labels:
        com.librenms.service: "cache"
        com.librenms.description: "Redis cache for LibreNMS"
    networks:
      - librenms
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - SYS_RESOURCE
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  librenms:
    image: librenms/librenms:23.11.0
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '2'
          memory: 2G
      labels:
        com.librenms.service: "application"
        com.librenms.description: "LibreNMS network monitoring system"
    environment:
      DB_HOST: db
      DB_NAME: librenms
      DB_USER: librenms
      DB_PASSWORD: ${DB_PASSWORD:-librenms_password}
      REDIS_HOST: redis
      # Required timezone, adjust as needed
      TZ: ${TZ:-UTC}
      # Adjust this to your actual domain or IP
      BASE_URL: ${BASE_URL:-http://localhost}
      ENABLE_DISTRIBUTED_POLLING: "true"
      # Store RRD data in the database for better compatibility
      DB_RRD: "true"
    volumes:
      - librenms-data:/data
    # Wait for database to be ready
    depends_on:
      - db
      - redis
      - memcached
    entrypoint: ["/bin/sh", "-c", "until mysqladmin ping -h db --silent; do sleep 5; done; /init"]
    ports:
      - "${WEB_PORT:-8080}:8000"
    networks:
      - librenms
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - SETGID
      - SETUID
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  memcached:
    image: memcached:alpine
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      labels:
        com.librenms.service: "cache"
        com.librenms.description: "Memcached for LibreNMS"
    networks:
      - librenms
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - SYS_RESOURCE
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "11211"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Self-contained backup service that doesn't require external scripts
  backup:
    image: alpine:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      labels:
        com.librenms.service: "backup"
        com.librenms.description: "Backup service for LibreNMS"
    volumes:
      - db-data:/source/db:ro
      - librenms-data:/source/librenms:ro
      - backup-volume:/backup
    networks:
      - librenms
    # Install required tools and set up backup automation
    command: >
      sh -c "apk add --no-cache mariadb-client tzdata &&
             mkdir -p /backup/db /backup/librenms &&
             echo '0 2 * * * /bin/sh -c \"mysqldump -h db -u librenms -p${DB_PASSWORD} --single-transaction --quick --lock-tables=false librenms | gzip > /backup/db/librenms_db_\$$(date +\\%Y\\%m\\%d_\\%H\\%M\\%S).sql.gz && find /backup/db -name \"librenms_db_*.sql.gz\" -type f -mtime +7 -delete\"' > /var/spool/cron/crontabs/root &&
             echo '0 3 * * * /bin/sh -c \"tar -czf /backup/librenms/librenms_app_\$$(date +\\%Y\\%m\\%d_\\%H\\%M\\%S).tar.gz -C /source/librenms . && find /backup/librenms -name \"librenms_app_*.tar.gz\" -type f -mtime +7 -delete\"' >> /var/spool/cron/crontabs/root &&
             chmod 600 /var/spool/cron/crontabs/root &&
             crond -f -d 8"
    environment:
      - DB_PASSWORD=${DB_PASSWORD:-librenms_password}

# Persistent storage
volumes:
  db-data:
    driver: local
  librenms-data:
    driver: local
  backup-volume:
    driver: local

networks:
  librenms:
    driver: overlay
    attachable: true

# Config files embedded in the stack
configs:
  mariadb_config_v4:
    content: |
      [mysqld]
      # Security Settings
      skip-networking=0
      bind-address=0.0.0.0
      local-infile=0
      symbolic-links=0
      # Explicitly set secure-file-priv to NULL to disable this feature
      secure-file-priv=NULL

      # User limits
      max_connections=100
      max_user_connections=50
      max_connect_errors=10000
      connect_timeout=5

      # Query limits - prevent CPU/memory abuse
      max_allowed_packet=16M
      tmp_table_size=64M
      max_heap_table_size=64M
      thread_cache_size=128
      query_cache_type=0
      query_cache_size=0

      # InnoDB settings
      innodb_file_per_table=1
      innodb_buffer_pool_size=256M
      innodb_buffer_pool_instances=1
      innodb_flush_log_at_trx_commit=1
      innodb_log_buffer_size=16M
      innodb_log_file_size=64M
      innodb_strict_mode=1

      # Logging
      general_log=0
      slow_query_log=1
      slow_query_log_file=/var/log/mysql/mysql-slow.log
      long_query_time=2
      log_error=/var/log/mysql/error.log

      # Character set and collation
      character-set-server=utf8mb4
      collation-server=utf8mb4_unicode_ci

      # Disable potentially dangerous functions
      sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY